# 1.1 - Numpy  (Numerical Python)

**[Documentación](https://numpy.org/doc/stable/)**

**[Código fuente](https://github.com/numpy/numpy)**


![numpy](images/numpy.png)

NumPy es el paquete fundamental para computación cientifíca en python. Es una librería de python nos permite manejar vectores, matrices, [tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) (arrays multidimensionales) y además realizar todas las operaciones matemáticas y lógicas de los mismos, como la manipulación de la dimensión, ordenado, selección, I/O, operaciones estadísticas, transformadas de Fourier, simulación aleatoria y un largo etcétera. Constituye la herramienta de álgebra lineal.

## Recordatorio de álgebra

+ Contenidos:

    + Concepto de tensor
    + Operaciones con vectores
        + Concepto de espacio vectorial y base
        + Suma de vectores
        + Producto escalar
        + Producto vectorial
    + Operaciones con matrices
        + Suma de matrices
        + Producto matricial
        + Matriz Identidad
        + Matriz Traspuesta (Hermítica)
        + Matriz Inversa 
        + Determinate

### Tensor

La palabra ['tensor'](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) se utiliza a menudo como abreviatura de campo tensorial, que es un valor tensorial definido en cada punto en una variedad. El primero en utilizar esta palabra fue William Rowan Hamilton en 1846, empleándola para lo que actualmente se conoce como módulo y fue Woldemar Voigt en 1899 quien la empleó en su acepción actual. La palabra tensor proviene del latín tensus, participio pasado de tendere 'estirar, extender'. El nombre se extendió porque la teoría de la elasticidad fue una de las primeras aplicaciones físicas donde se usaron tensores. Gregorio Ricci-Curbastro en 1890 desarrolló la notación actual con el nombre de geometría diferencial absoluta, y se popularizó con la publicación de Cálculo Diferencial Absoluto de Tullio Levi-Civita en 1900. Con la introducción de la teoría de la relatividad general por parte de Albert Einstein alrededor de 1915 se encontró su aplicación más pragmática. La Relatividad General es netamente tensorial. Einstein había aprendido del mismo Levi-Civita el uso de tensores con gran dificultad.

Podemos pensar en un tensor como la generalización del ente algebraico. Con un ejemplo se verá más claro.

Un **número**, cualquier número, $2$, $3.6$, $\pi$, $\phi$, $\sqrt{2}$, es un **tensor de rango $0$**.

Un **vector**, cualquier vector, sea como sea su longitud, $(1, 2, 3)$, $(0, 5, 2, 1, 5)$, $(9,2)$, es un **tensor de rango $1$**.

Una **matriz**, cualquier matriz, sean cuales sean sus dimensiones, es un **tensor de rango $2$**.

Un **cubo de Rubik** por ejemplo es un **tensor de rango $3$**.

Pensar en dimensiones superiores es complicado por no decir imposible, pero se pueden interpretar a través del contenido. Una **bolsa llena de cubos de Rubik** es un **tensor de rango $4$**.

Una **caja llena de bolsas que están llenas de cubos de Rubik es un tensor de rango $5$**.

Y así sucesivamente.

### Operaciones con vectores

**Espacio vectorial**

La definición matemática de [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) implica los conceptos de conjunto, ley de composición(operación) interna y ley de composición externa, definida sobre un segundo conjunto. Resumiendo, un espacio vectorial es una estructura creada sobre un conjunto no vacío con ambas leyes de composición. A los elementos de un espacio vectorial se les llama vectores.

Veamos un ejemplo:

Un espacio vectorial es el espacio tridimensional ${\Bbb R}^{3}$. Los elementos de ${\Bbb R}^{3}$ son vectores, por lo que la ley de composición interna es la suma de vectores. Para la ley de composición externa se necesita otro conjunto, que en esta caso son los números reales ${\Bbb R}$, y queda definida como el producto por escalares, multiplicar un vector por un número.



**Base vectorial**

Una [base](https://es.wikipedia.org/wiki/Base_(%C3%A1lgebra)) es un conjunto de vectores {$v_{1}, v_{2}, v_{3}, ... ,v_{n}$} que cumplen las siguientes propiedades:

+ Todos los elementos de la base pertenecen al mismo espacio vectorial.
+ Los elementos de la base forman un sistema linealmente independiente (ninguno es combinación lineal de los demás).
+ Cualquier elemento del espacio vectorial se puede escribir como combinación lineal de los elementos de la base (es lo que se llama sistema generador del espacio vectorial).

Ejemplo:

En ${\Bbb R}^{3}$, la base principal (llamada canónica) es {$(1,0,0), (0,1,0), (0,0,1)$}. Todos esos vectores pertenecen a ${\Bbb R}^{3}$, son linealmente independientes(ninguno puede ser una suma de los otros) y cualquier otro vector en ${\Bbb R}^{3}$ se puede representar como una suma de esos tres, una combinación lineal. No es única, otra base de ${\Bbb R}^{3}$ podría ser {$(1,1,1), (1,1,0), (1,0,0)$}



**Suma de vectores**

Los vectores se suman por componentes, lo que implica que ambos tienen la misma longitud. Por ejemplo en ${\Bbb R}^{3}$:

$$\vec{A}=A_{x}\vec{i}+A_{y}\vec{j}+A_{z}\vec{k}$$

$$\vec{B}=B_{x}\vec{i}+B_{y}\vec{j}+B_{z}\vec{k}$$

$$\vec{A}+\vec{B}=(B_{x}+A_{x})\vec{i}+(B_{y}+A_{y})\vec{j}+(B_{z}+A_{z})\vec{k}$$

$$$$

$$\vec{A}=(1,8,9)$$

$$\vec{B}=(4,3,0)$$

$$\vec{A}+\vec{B}=(5,11,9)$$



**Producto escalar**

Hay que diferenciar entre producto por escalares, un número por un vector resultando un vector, y el productor escalar donde se multiplican dos vectores resultando un número, un escalar.

+ Producto por escalares:

Se realiza elemento a elemento la multiplicación por el número:

$$\vec{A}=(1,8,9)$$

$$2*\vec{A}=(2,16,18)$$

+ Productos escalar:

Se realiza multiplicando elemento un vector fila por un vector columna y sumando los resultados. Hay que tener en cuenta, igual que en la suma, que ambos vectores tienen el mismo número de elementos. También se le llama producto punto (dot product) o producto interno (inner product).

$$\vec{A}\cdot\vec{B}=(1, 8, 9)\cdot\begin{pmatrix}4\\3\\0\end{pmatrix} = 1·4+8·3+9·0 = 4+24+0 = 28$$



**Producto vectorial**

En este caso, se multiplican dos vectores resultando otro vector. La manera más fácil de hacerlo es a través de un determinante:


$$\vec{A}\times \vec{B} = \begin{vmatrix}
\hat{\imath}&\hat{\jmath}&\hat{k}\\
1 & 8 & 9 \\
4 & 3 & 0
\end{vmatrix} = \begin{vmatrix}
8 & 9 \\
3 & 0
\end{vmatrix}·\hat{\imath} - 
\begin{vmatrix}
1 & 9 \\
4 & 0
\end{vmatrix}·\hat{\jmath} +
\begin{vmatrix}
1 & 8 \\
4 & 3
\end{vmatrix}·\hat{k} = (8·0-9·3)·\hat{\imath}-(1·0-9·4)·\hat{\jmath}+(1·3-8·4)·\hat{k}$$

$$\vec{A}\times \vec{B} = (-27, 36, -29)$$

### Operaciones con matrices


**Suma de matrices**

Las matrices tienen definidas sus dimensiones sugún el número de filas($m$) y de columnas($n$), y se representan como $A_{mxn}$. Para sumar matrices las dimensiones tienen que ser las mismas, igual que ocurría con los vectores, y se realiza elemento a elemento (element wise):


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}+\begin{pmatrix}
0 & 0 & 3 \\
2 & 2 & 7 
\end{pmatrix}=\begin{pmatrix}
5 & 7 & 4 \\
6 & 2 & 9 
\end{pmatrix}$$



**Producto matricial**

Para multiplicar matrices tenemos que tener en cuenta las dimensiones, porque el producto matricial no es conmutativo e incluso a veces no se puede realizar. El número de columnas de la primera matriz tiene que ser igual que el número de filas de la segunda y el resultado tendrá el número de filas de la primera y el número de columnas de la segunda. Es decir:

$$A_{rxn}\cdot B_{nxq} = C_{rxq}$$


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}\cdot\begin{pmatrix}
0 & 0 \\
2 & 3 \\
2 & 7 
\end{pmatrix}=\begin{pmatrix}
5·0+7·2+1·2 & 5·0+7·3+1·7 \\
4·0+0·2+2·2 & 4·0+0·3+2·7
\end{pmatrix}=\begin{pmatrix}
18 & 28 \\
4 & 14
\end{pmatrix}$$



**Matriz Identidad**

Elemento neutro de la multiplicación, solo $1_s$ en la diagonal:

$$I = \begin{pmatrix}
1&0&\cdots&0&0\\
0&1&\cdots&0&0\\
\vdots&\vdots&\ddots&\vdots&\vdots\\
0&\cdots&\cdots&\cdots&0\\
0&0&\cdots&1&0\\
0&0&\cdots&0&1\\
\end{pmatrix}$$



**Matriz traspuesta  (hermítica)**

La traspuesta $A^{T}$ de una matriz $A$ puede ser obtenida reflejando los elementos a lo largo de su diagonal.

$$A=\begin{pmatrix}
5 & 7 & 9 \\
4 & 0 & 7 \\
1 & 2 & 2
\end{pmatrix}$$

$$A^{T}=\begin{pmatrix}
5 & 4 & 1 \\
7 & 0 & 2 \\
9 & 7 & 2
\end{pmatrix}$$


Se le dice hermítica si los elementos son números complejos, es la traspuesta conjugada (el conjugado de $x+iy$ es $x-iy$).


**Matriz Inversa**

¿Como se dividen las matrices? Se multiplica por la inversa. El cálculo de la matriz inversa es:

$$A= \begin{pmatrix}
       a_{11} & a_{12} \\ 
       a_{21} & a_{22}
    \end{pmatrix}$$
    
    
$$A^{-1}=\begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}^{-1}
=\frac{1}{\lvert A\rvert}
\begin{pmatrix}
a_{22} & -a_{12} \\ 
-a_{21} &  a_{11}
\end{pmatrix}$$


**Determinante**

$$A=\begin{pmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{pmatrix}$$
  

$$$$


$$det(A)=\begin{vmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 0 & 0 \\ 
    -2 & 1 & 0 \\ 
    -2 & 0 & 1
  \end{vmatrix}\cdot
  \begin{vmatrix}
    1 & 4 & 1 \\ 
    2 & 6 & 3 \\ 
    2 & 10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 4 & 1 \\ 
    0 & -2 & 1 \\ 
    0 & 2 & 1
  \end{vmatrix}
  =
  \begin{vmatrix}
    -2 & 1 \\ 
    2 & 1
  \end{vmatrix}
  =-4$$
  
  

**Veamos algo de todo esto en python:**


**Arrays**

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [11]:
# numero aleatorio

np.random.random(1)

array([0.30174463])

In [13]:
type(np.random.random(1))

numpy.ndarray

In [15]:
type(np.random.random(1)[0])

numpy.float64

In [4]:
# vector, tensor de rango 1

vector=np.random.random(5)  # numeros aleatorios uniformente distribuidos entre 0 y 1, 5 elementos

vector

array([0.19741496, 0.34845641, 0.37524682, 0.78202895, 0.26474238])

In [16]:
type(vector)

numpy.ndarray

In [17]:
2 * vector

array([0.39482993, 0.69691282, 0.75049364, 1.5640579 , 0.52948476])

In [18]:
2 * [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

In [19]:
# matriz, tensor de rango 2

matriz=np.random.random((10, 4))

matriz

array([[0.15372371, 0.34265806, 0.15718253, 0.56976368],
       [0.11973839, 0.32088182, 0.63864844, 0.58365115],
       [0.17492646, 0.95241757, 0.68641328, 0.63566256],
       [0.67595219, 0.71980948, 0.70652528, 0.94818533],
       [0.34596682, 0.84253526, 0.3314432 , 0.43784752],
       [0.23440098, 0.86855672, 0.43454162, 0.65705182],
       [0.16915237, 0.48798469, 0.37072208, 0.5337954 ],
       [0.01908357, 0.59999184, 0.33741442, 0.23252542],
       [0.64745895, 0.04306629, 0.94508971, 0.93215011],
       [0.16788576, 0.64674132, 0.08899431, 0.36268463]])

In [20]:
type(matriz)

numpy.ndarray

In [22]:
matriz.shape  # dimesiones

(10, 4)

In [23]:
matriz.size   # nº de elementos

40

In [24]:
len(matriz)

10

In [25]:
matriz[0]  # primera fila

array([0.15372371, 0.34265806, 0.15718253, 0.56976368])

In [26]:
matriz[0][-1]

0.5697636767520081

In [27]:
matriz[:, 0]   # primera columna

array([0.15372371, 0.11973839, 0.17492646, 0.67595219, 0.34596682,
       0.23440098, 0.16915237, 0.01908357, 0.64745895, 0.16788576])

In [28]:
matriz[:, 0].shape

(10,)

In [32]:
lst=[1,2,3]

array=np.array(lst)

In [33]:
array.shape

(3,)

In [34]:
lst.shape

AttributeError: 'list' object has no attribute 'shape'

In [35]:
# cubo, tensor de rango 3

cubo=np.random.random((3, 3, 2))

cubo

array([[[0.92088045, 0.43036555],
        [0.02812151, 0.67996859],
        [0.07505487, 0.39461804]],

       [[0.69952577, 0.40064109],
        [0.02336649, 0.16876855],
        [0.31089447, 0.89837733]],

       [[0.85342001, 0.05856203],
        [0.61875264, 0.45268514],
        [0.03088114, 0.83878626]]])

In [36]:
# tensor de rango 4

tensor=np.random.random((2, 3, 4, 5))

tensor

array([[[[0.19015647, 0.76843918, 0.52316692, 0.71786022, 0.88744423],
         [0.7925322 , 0.57244168, 0.45553811, 0.03498928, 0.74199982],
         [0.07972438, 0.75091895, 0.00935444, 0.73005446, 0.65144651],
         [0.16079611, 0.26795618, 0.12477688, 0.99300497, 0.08181152]],

        [[0.98449306, 0.06116139, 0.02043976, 0.91755882, 0.77627568],
         [0.18676411, 0.94978049, 0.43481778, 0.1067167 , 0.95348748],
         [0.45719135, 0.71324188, 0.30174693, 0.66848755, 0.95344701],
         [0.98342781, 0.35453683, 0.11211605, 0.94133282, 0.83340273]],

        [[0.04122517, 0.32585575, 0.05614433, 0.37077306, 0.07307626],
         [0.05140621, 0.06615047, 0.19579725, 0.00965714, 0.67907072],
         [0.70748951, 0.1234116 , 0.56334173, 0.76489274, 0.72561045],
         [0.56030962, 0.7072955 , 0.23736768, 0.85831564, 0.83269643]]],


       [[[0.22829097, 0.88463207, 0.95069545, 0.35703086, 0.42036361],
         [0.44569917, 0.11046868, 0.75614663, 0.95857546, 0.54289327]

In [37]:
tensor.shape

(2, 3, 4, 5)

In [38]:
tensor[0]   # el primer cubo en la bolsa

array([[[0.19015647, 0.76843918, 0.52316692, 0.71786022, 0.88744423],
        [0.7925322 , 0.57244168, 0.45553811, 0.03498928, 0.74199982],
        [0.07972438, 0.75091895, 0.00935444, 0.73005446, 0.65144651],
        [0.16079611, 0.26795618, 0.12477688, 0.99300497, 0.08181152]],

       [[0.98449306, 0.06116139, 0.02043976, 0.91755882, 0.77627568],
        [0.18676411, 0.94978049, 0.43481778, 0.1067167 , 0.95348748],
        [0.45719135, 0.71324188, 0.30174693, 0.66848755, 0.95344701],
        [0.98342781, 0.35453683, 0.11211605, 0.94133282, 0.83340273]],

       [[0.04122517, 0.32585575, 0.05614433, 0.37077306, 0.07307626],
        [0.05140621, 0.06615047, 0.19579725, 0.00965714, 0.67907072],
        [0.70748951, 0.1234116 , 0.56334173, 0.76489274, 0.72561045],
        [0.56030962, 0.7072955 , 0.23736768, 0.85831564, 0.83269643]]])

In [39]:
tensor[0][0]

array([[0.19015647, 0.76843918, 0.52316692, 0.71786022, 0.88744423],
       [0.7925322 , 0.57244168, 0.45553811, 0.03498928, 0.74199982],
       [0.07972438, 0.75091895, 0.00935444, 0.73005446, 0.65144651],
       [0.16079611, 0.26795618, 0.12477688, 0.99300497, 0.08181152]])

In [44]:
tensor[0][0][:, 0][-1]

0.16079610661022836

In [42]:
#help(tensor)

**Operaciones matemáticas**

In [45]:
matriz

array([[0.15372371, 0.34265806, 0.15718253, 0.56976368],
       [0.11973839, 0.32088182, 0.63864844, 0.58365115],
       [0.17492646, 0.95241757, 0.68641328, 0.63566256],
       [0.67595219, 0.71980948, 0.70652528, 0.94818533],
       [0.34596682, 0.84253526, 0.3314432 , 0.43784752],
       [0.23440098, 0.86855672, 0.43454162, 0.65705182],
       [0.16915237, 0.48798469, 0.37072208, 0.5337954 ],
       [0.01908357, 0.59999184, 0.33741442, 0.23252542],
       [0.64745895, 0.04306629, 0.94508971, 0.93215011],
       [0.16788576, 0.64674132, 0.08899431, 0.36268463]])

In [46]:
matriz.sum()   # lo suma todo

19.12322475503144

In [48]:
np.sum(matriz)

19.12322475503144

In [49]:
matriz.sum(axis=0)   # suma por columnas

array([2.70828922, 5.82464306, 4.69697486, 5.89331762])

In [50]:
matriz.sum(axis=1)   # suma por filas

array([1.22332798, 1.6629198 , 2.44941987, 3.05047229, 1.9577928 ,
       2.19455115, 1.56165454, 1.18901525, 2.56776507, 1.26630601])

In [51]:
matriz.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [56]:
cubo.sum(axis=2)

array([[1.351246  , 0.70809011, 0.46967291],
       [1.10016686, 0.19213504, 1.2092718 ],
       [0.91198204, 1.07143778, 0.8696674 ]])

In [57]:
tensor.shape

(2, 3, 4, 5)

In [58]:
tensor.sum(axis=0).shape     # suma por cubos

(3, 4, 5)

In [59]:
tensor.sum(axis=1).shape     # suma por capas del cubo

(2, 4, 5)

In [60]:
tensor.sum(axis=2).shape     # suma por filas

(2, 3, 5)

In [61]:
tensor.sum(axis=3).shape     # suma por columnas

(2, 3, 4)

In [62]:
matriz.min()

0.019083565604517072

In [63]:
matriz.max()

0.9524175673303878

In [66]:
matriz[0:2, 0:2].max()

0.342658064014433

In [67]:
matriz.mean()  # media de todo

0.478080618875786

In [68]:
matriz.mean(axis=0)

array([0.27082892, 0.58246431, 0.46969749, 0.58933176])

In [69]:
matriz.std()

0.2714509346376362

In [70]:
matriz.var()

0.07368560991564624

In [71]:
matriz.var(axis=0)

array([0.04429981, 0.07354627, 0.0647841 , 0.04581595])

In [72]:
matriz.var() ** 0.5

0.2714509346376362

In [75]:
np.add(matriz[0], matriz[1])  # suma de vectores

array([0.27346211, 0.66353989, 0.79583096, 1.15341483])

In [76]:
np.subtract(matriz[0], matriz[1])# resta de vectores

array([ 0.03398532,  0.02177624, -0.48146591, -0.01388747])

In [77]:
np.prod(matriz)  # productorio

4.9725419585720295e-18

In [78]:
1e3   # notacion cientifica

1000.0

In [79]:
1e-3 

0.001

In [80]:
np.multiply(matriz[0], matriz[1])   # elemento a elemento

array([0.01840663, 0.10995274, 0.10038437, 0.33254322])

In [81]:
matriz[0]

array([0.15372371, 0.34265806, 0.15718253, 0.56976368])

In [82]:
matriz[1]

array([0.11973839, 0.32088182, 0.63864844, 0.58365115])

In [84]:
np.dot(matriz[0], matriz[1])    # producto escalar

0.5612869736469129

In [87]:
np.dot(matriz, matriz.T).shape

(10, 10)

In [88]:
np.matmul(matriz, matriz.T).shape

(10, 10)

In [91]:
matriz.T

array([[0.15372371, 0.11973839, 0.17492646, 0.67595219, 0.34596682,
        0.23440098, 0.16915237, 0.01908357, 0.64745895, 0.16788576],
       [0.34265806, 0.32088182, 0.95241757, 0.71980948, 0.84253526,
        0.86855672, 0.48798469, 0.59999184, 0.04306629, 0.64674132],
       [0.15718253, 0.63864844, 0.68641328, 0.70652528, 0.3314432 ,
        0.43454162, 0.37072208, 0.33741442, 0.94508971, 0.08899431],
       [0.56976368, 0.58365115, 0.63566256, 0.94818533, 0.43784752,
        0.65705182, 0.5337954 , 0.23252542, 0.93215011, 0.36268463]])

In [93]:
matriz.transpose()

array([[0.15372371, 0.11973839, 0.17492646, 0.67595219, 0.34596682,
        0.23440098, 0.16915237, 0.01908357, 0.64745895, 0.16788576],
       [0.34265806, 0.32088182, 0.95241757, 0.71980948, 0.84253526,
        0.86855672, 0.48798469, 0.59999184, 0.04306629, 0.64674132],
       [0.15718253, 0.63864844, 0.68641328, 0.70652528, 0.3314432 ,
        0.43454162, 0.37072208, 0.33741442, 0.94508971, 0.08899431],
       [0.56976368, 0.58365115, 0.63566256, 0.94818533, 0.43784752,
        0.65705182, 0.5337954 , 0.23252542, 0.93215011, 0.36268463]])

In [96]:
np.cross(matriz[0][:3], matriz[1][:3])  # producto vectorial

array([ 0.16840102, -0.07935463,  0.00829782])

In [97]:
np.tensordot(matriz, matriz)

array(12.08986752)

In [98]:
matriz.cumsum()

array([ 0.15372371,  0.49638178,  0.6535643 ,  1.22332798,  1.34306637,
        1.6639482 ,  2.30259663,  2.88624778,  3.06117424,  4.01359181,
        4.70000509,  5.33566765,  6.01161984,  6.73142932,  7.4379546 ,
        8.38613994,  8.73210676,  9.57464202,  9.90608522, 10.34393274,
       10.57833372, 11.44689044, 11.88143206, 12.53848388, 12.70763626,
       13.19562095, 13.56634303, 14.10013842, 14.11922199, 14.71921383,
       15.05662825, 15.28915368, 15.93661263, 15.97967892, 16.92476863,
       17.85691874, 18.0248045 , 18.67154582, 18.76054013, 19.12322476])

In [99]:
matriz.cumprod()

array([1.53723714e-01, 5.26746702e-02, 8.27953772e-03, 4.71737985e-03,
       5.64851488e-04, 1.81250575e-04, 1.15755396e-04, 6.75607699e-05,
       1.18181663e-05, 1.12558292e-05, 7.72615067e-06, 4.91122470e-06,
       3.31975311e-06, 2.38958977e-06, 1.68830557e-06, 1.60082658e-06,
       5.53832888e-07, 4.66623734e-07, 1.54659265e-07, 6.77171753e-08,
       1.58729725e-08, 1.37865769e-08, 5.99084149e-09, 3.93629332e-09,
       6.65833359e-10, 3.24916488e-10, 1.20453715e-10, 6.42976385e-11,
       1.22702820e-12, 7.36206909e-13, 2.48406830e-13, 5.77609035e-14,
       3.73978141e-14, 1.61058529e-15, 1.52214758e-15, 1.41887004e-15,
       2.38208074e-16, 1.54059004e-16, 1.37103742e-17, 4.97254196e-18])

In [100]:
np.nan

nan

In [101]:
np.inf

inf

In [102]:
type(np.inf)

float

**Dimensiones**

In [103]:
matriz.shape

(10, 4)

In [104]:
matriz.reshape((5, 8))

array([[0.15372371, 0.34265806, 0.15718253, 0.56976368, 0.11973839,
        0.32088182, 0.63864844, 0.58365115],
       [0.17492646, 0.95241757, 0.68641328, 0.63566256, 0.67595219,
        0.71980948, 0.70652528, 0.94818533],
       [0.34596682, 0.84253526, 0.3314432 , 0.43784752, 0.23440098,
        0.86855672, 0.43454162, 0.65705182],
       [0.16915237, 0.48798469, 0.37072208, 0.5337954 , 0.01908357,
        0.59999184, 0.33741442, 0.23252542],
       [0.64745895, 0.04306629, 0.94508971, 0.93215011, 0.16788576,
        0.64674132, 0.08899431, 0.36268463]])

In [106]:
matriz.flatten().shape

(40,)

In [107]:
matriz + np.array([1, 2, 3, 4])

array([[1.15372371, 2.34265806, 3.15718253, 4.56976368],
       [1.11973839, 2.32088182, 3.63864844, 4.58365115],
       [1.17492646, 2.95241757, 3.68641328, 4.63566256],
       [1.67595219, 2.71980948, 3.70652528, 4.94818533],
       [1.34596682, 2.84253526, 3.3314432 , 4.43784752],
       [1.23440098, 2.86855672, 3.43454162, 4.65705182],
       [1.16915237, 2.48798469, 3.37072208, 4.5337954 ],
       [1.01908357, 2.59999184, 3.33741442, 4.23252542],
       [1.64745895, 2.04306629, 3.94508971, 4.93215011],
       [1.16788576, 2.64674132, 3.08899431, 4.36268463]])

In [108]:
matriz + [1, 2, 3, 4]

array([[1.15372371, 2.34265806, 3.15718253, 4.56976368],
       [1.11973839, 2.32088182, 3.63864844, 4.58365115],
       [1.17492646, 2.95241757, 3.68641328, 4.63566256],
       [1.67595219, 2.71980948, 3.70652528, 4.94818533],
       [1.34596682, 2.84253526, 3.3314432 , 4.43784752],
       [1.23440098, 2.86855672, 3.43454162, 4.65705182],
       [1.16915237, 2.48798469, 3.37072208, 4.5337954 ],
       [1.01908357, 2.59999184, 3.33741442, 4.23252542],
       [1.64745895, 2.04306629, 3.94508971, 4.93215011],
       [1.16788576, 2.64674132, 3.08899431, 4.36268463]])

In [110]:
vector + 10

array([10.19741496, 10.34845641, 10.37524682, 10.78202895, 10.26474238])

In [116]:
np.where(matriz>0.5, 1, 0)

array([[0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 0]])

In [117]:
matriz

array([[0.15372371, 0.34265806, 0.15718253, 0.56976368],
       [0.11973839, 0.32088182, 0.63864844, 0.58365115],
       [0.17492646, 0.95241757, 0.68641328, 0.63566256],
       [0.67595219, 0.71980948, 0.70652528, 0.94818533],
       [0.34596682, 0.84253526, 0.3314432 , 0.43784752],
       [0.23440098, 0.86855672, 0.43454162, 0.65705182],
       [0.16915237, 0.48798469, 0.37072208, 0.5337954 ],
       [0.01908357, 0.59999184, 0.33741442, 0.23252542],
       [0.64745895, 0.04306629, 0.94508971, 0.93215011],
       [0.16788576, 0.64674132, 0.08899431, 0.36268463]])

In [118]:
lst_lst=[[12, 3, 4], [3, 4, 5], [6, 7, 8]]

lst_lst

[[12, 3, 4], [3, 4, 5], [6, 7, 8]]

In [120]:
np.array(lst_lst).shape

(3, 3)

In [121]:
np.array(['hola', 'adios'])

array(['hola', 'adios'], dtype='<U5')

In [122]:
vector.dtype

dtype('float64')

In [123]:
np.array(['hola', 'adios']).dtype

dtype('<U5')